"""Add role column to messages table

Revision ID: 73a9427edcc2
Revises: 953ea94f102a
Create Date: 2025-10-31 10:54:56.540662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a9427edcc2'
down_revision: Union[str, Sequence[str], None] = '953ea94f102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the column with a default value for existing rows
    op.add_column(
        'messages',
        sa.Column('role', sa.String(), nullable=False, server_default='user')
    )

    # Optionally remove default after migration if you don't want it at DB level
    op.alter_column('messages', 'role', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
