"""add pending_action column to ChatSession

Revision ID: 953ea94f102a
Revises: 5c881143ebfb
Create Date: 2025-10-31 10:23:03.677057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953ea94f102a'
down_revision: Union[str, Sequence[str], None] = '5c881143ebfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pending_action', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'pending_action')
    # ### end Alembic commands ###
