"""add pending_action to sessions

Revision ID: 5c881143ebfb
Revises: e9330549436f
Create Date: 2025-10-30 18:40:47.109947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c881143ebfb'
down_revision: Union[str, Sequence[str], None] = 'e9330549436f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'pending_action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('pending_action', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
